config-version = 2
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true
persistent-workspaces = ["browser", "slack", "terminal", "obsidian", "coding"]
on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

# Would be nice if this supported per app.id gaps
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # use < > to resize
    alt-shift-comma = 'resize smart -50'
    alt-shift-period = 'resize smart +50'

    alt-1 = 'workspace browser'
    alt-2 = 'workspace slack'
    alt-3 = 'workspace terminal'
    alt-8 = 'workspace coding'
    alt-9 = 'workspace obsidian'
    alt-slash = 'workspace tmp'

    alt-shift-1 = 'move-node-to-workspace browser'
    alt-shift-2 = 'move-node-to-workspace slack'
    alt-shift-3 = 'move-node-to-workspace terminal'
    alt-shift-8 = 'move-node-to-workspace coding'
    alt-shift-9 = 'move-node-to-workspace obsidian'
    # move a window to a temporary workspace
    alt-shift-slash = 'move-node-to-workspace tmp'

    # alt-tab = 'workspace --wrap-around next'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

[[on-window-detected]]
    if.app-id = 'app.zen-browser.zen'
    run = ['move-node-to-workspace --focus-follows-window browser']
[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    run = ['layout tiling', 'move-node-to-workspace --focus-follows-window slack']
[[on-window-detected]]
    if.app-id = 'com.microsoft.Outlook'
    run = ['layout tiling', 'move-node-to-workspace --focus-follows-window slack']
[[on-window-detected]]
    if.app-id = 'com.github.wez.wezterm'
    run = ['move-node-to-workspace --focus-follows-window terminal']
[[on-window-detected]]
    if.app-id = 'dev.zed.Zed'
    run = ['layout floating', 'move-node-to-workspace --focus-follows-window coding']
[[on-window-detected]]
    if.app-id = 'com.jetbrains.intellij'
    run = ['layout floating', 'move-node-to-workspace --focus-follows-window coding']
[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = ['move-node-to-workspace --focus-follows-window obsidian']
